insert into `lf_employee` (loginName,passWord,status,grade,createtime) values('admin','111111',1,0,now());


INSERT INTO `lf_company` (`id`, `companyName`, `cityId`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`,`userName`,`companyProfile`) VALUES ('966', '上海好居', '43', '13901636269', '长乐路1219号长鑫大厦12楼', NULL, '1', now(), now(),'13901636269','上海好居');
INSERT INTO `lf_company` (`id`, `companyName`, `cityId`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`,`userName`,`companyProfile`) VALUES ('967', '上海志远', '43', '13901636269', '长乐路1219号长鑫大厦12楼', NULL, '1', now(), now(),'13901636269','上海志远');


INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('1', '上海好居总部', '966', '43', '0', '0', '31103127', '长乐路1219号长鑫大厦12楼', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('236', '镇宁C组', '967', '43', '0', '0', '31103127', '长宁区镇宁路87号甲近延安西路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('239', '商办一部', '967', '43', '0', '0', '31103154', '胶州路941号长久商务中心1201室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('240', '新里洋房部', '967', '43', '0', '0', '31103167', '徐汇区复兴西路197号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('241', '天汇店', '967', '43', '0', '0', '31103195', '上海市长宁区镇宁路447号（近万航渡路）', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('242', '镇宁A组', '967', '43', '0', '0', '31103128', '长宁区镇宁路87号甲近延安西路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('244', '淮海店', '967', '43', '0', '0', '31103120', '徐汇区淮海中路1640号近湖南路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('245', '霞飞店', '967', '43', '0', '0', '51698633', '徐汇区淮海中路1640号近湖南路（上海图', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('248', '武康店', '967', '43', '0', '0', '31103167', '复兴西路199号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('249', '徐汇一店', '967', '43', '0', '0', '31103180', '龙华路2321号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('250', '华漕店', '967', '43', '0', '0', '31103179', '闵行区金丰路442号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('252', '商办二部', '967', '43', '0', '0', '31103158', '普陀区胶州路941号长久商务中心1201', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('253', '商办三部', '967', '43', '0', '0', '31103153', '胶州路941号长久商务中心1201室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('254', '商办六部', '967', '43', '0', '0', '31103161', '普陀区胶州路941号长久商务中心1201', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('256', '鸿艺店', '967', '43', '0', '0', '31103173', '淮海中路1558号（近乌鲁木齐中路）', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('257', '天山B组', '967', '43', '0', '0', '31103191', '上海市长宁区安化路560号近凯旋路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('259', '住宅科', '967', '43', '0', '0', NULL, NULL, NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('264', '徐虹A组', '967', '43', '0', '0', '31103128', '虹桥路608号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('265', '中山公园A组', '967', '43', '0', '0', '31103189', '虹桥路608号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('270', '徐泾一店', '967', '43', '0', '0', '31103122', '徐泾镇盈港东路2263号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('273', '镇宁B组', '967', '43', '0', '0', '31103128', '长宁区镇宁路87号甲近延安西路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('275', '高泾店', '967', '43', '0', '0', '31103125', '上海市青浦区高泾路818号（近沪清平公路）', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('277', '盈港一店', '967', '43', '0', '0', '31103122', '徐泾镇盈港东路2263号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('280', '商办五部', '967', '43', '0', '0', '31103165 ', '延安西路1221号泛太大厦2号楼402室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('361', '中一区区部', '967', '43', '0', '0', '60190612', '医学院路69号华业大厦7C室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('363', '西区区部', '967', '43', '0', '0', '60901696', '徐汇区长乐路1219号长鑫大厦12楼', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('364', '商业地产部区部', '967', '43', '0', '0', '31103156', '延安西路1221号泛太大厦2号楼402室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('365', '别墅区区部', '967', '43', '0', '0', '31103179', '上海市', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('511', '商办七部', '967', '43', '0', '0', '31103165', '延安西路1221号泛太大厦2号楼402室', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('541', '华山店', '967', '43', '0', '0', '31103171', '华山路1553号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('571', '项目部', '967', '43', '0', '0', '60190606', '徐汇区长乐路1219号12层', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('691', '滨江店', '967', '43', '0', '0', '31103178', '龙华路2313号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('901', '徐虹B组', '967', '43', '0', '0', '31103169 ', '虹桥路608号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('902', '中山公园B组', '967', '43', '0', '0', '31103189', '上海市长宁区安化路560号', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('934', '沪青平店', '967', '43', '0', '0', '31103125 ', '上海市青浦区高泾路818号（近清平公路', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('964', '古北店', '967', '43', '0', '0', '31103197', '上海长宁区富贵东道308号-2', NULL, '1', now(), now());
INSERT INTO `lf_store` (`id`, `storeName`, `companyId`, `cityId`, `districtid`, `townid`, `mobile`, `address`, `mono`, `status`, `createTime`, `updateTime`) VALUES ('965', '商办松江分部', '967', '43', '0', '0', '31103614', '广富林路658弄255号1709室', NULL, '1', now(), now());